"""create runs table

Revision ID: aeef5fc2040a
Revises: 
Create Date: 2026-06-17 00:48:09.012938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeef5fc2040a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('policy_mode', sa.String(length=32), nullable=False),
    sa.Column('model_provider', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('input_hash', sa.String(length=128), nullable=True),
    sa.Column('raw_input_stored', sa.Boolean(), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=True),
    sa.Column('protected_prompt', sa.Text(), nullable=True),
    sa.Column('model_response', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runs')
    # ### end Alembic commands ###
